apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insiderone-devops-app.fullname" . }}
  labels:
    {{- include "insiderone-devops-app.labels" . | nindent 4 }}
data:
  APP_VERSION: {{ .Values.config.appVersion | quote }}
  GIT_SHA: {{ .Values.config.gitSha | quote }}
