{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "insiderone-devops-app.fullname" . }}
  labels:
    {{- include "insiderone-devops-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.values | nindent 2 }}
{{- end }}
