apiVersion: v1
kind: Service
metadata:
  name: {{ include "insiderone-devops-app.fullname" . }}
  labels:
    {{- include "insiderone-devops-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "insiderone-devops-app.selectorLabels" . | nindent 4 }}
