replicaCount: 2

image:
  repository: ghcr.io/ilke-demirkir/insiderone-devops-app
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: app.insiderone.local
      paths:
        - path: /
          pathType: Prefix

config:
  appVersion: "0.1.0"
  gitSha: replace-with-release-sha

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
