replicaCount: 1

image:
  repository: insiderone-devops-app
  tag: local
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: dev.insiderone.local
      paths:
        - path: /
          pathType: Prefix

config:
  appVersion: "0.1.0-dev"
  gitSha: local

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 250m
    memory: 192Mi
